name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main
      - improvement/docs-and-refactoring

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme  # Install Sphinx and themes
        pip install -r requirements.txt      # Install other dependencies from your project

    # Step 4: Build the Sphinx documentation
    - name: Build Sphinx documentation
      run: |
        cd docs
        make html  # This will build your docs into the _build/html directory

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
